[package]
name = "obelisk"
version = "0.1.0"
authors = ["Zicklag <zicklag@katharostech.com>"]
edition = "2018"

[dependencies]
shipyard = "0.4.1"
rustpython-compiler = "0.1.1"
rustpython-vm = "0.1.1"
